Modified DMM get_voltage function
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #124
Opened 2022-05-25 21:51 UTC by longsnn

Changed resolution parameter to PLC

2022-05-26 19:20 UTC, quintinstedman reviewed
I think the default range should be auto.

2022-05-26 21:17 UTC, longsnn commented
> I think the default range should be auto.

Thanks! I changed it. Let me know if I should change anything else.

2022-05-31 09:34 UTC, mofii requested changes
I made a bunch of comments within the code.
I'll discuss with Quintin the `PLC` vs `resolution` input parameter.
Please remove Quintin as a reviewer and add me instead.
Thanks,
Morten

2022-05-31 09:34 UTC, mofii commented on src/multimeter/keysight_common.jl
> +        instr::Instr{<:KeysightMultimeter}, # DMM Instrument
With this design, how do you support doc-strings for different multimeter models? And how do external users add more DMM models? (which have other allowed ranges and resolution combinations from the model that we have)

2022-05-31 09:34 UTC, mofii commented on src/multimeter/keysight_common.jl
> +        instr::Instr{<:KeysightMultimeter}, # DMM Instrument
Did you notice that you changed the API? I made the three last input arguments named arguments on pupose. Please re-introduce that.

2022-05-31 09:34 UTC, mofii commented on src/multimeter/keysight_common.jl
> +        instr::Instr{<:KeysightMultimeter}, # DMM Instrument
I'm not yet convinced that it's easier for the user to input `type`, `range`, and `plc` over `type`, `range` and `resolution`.

2022-05-31 09:34 UTC, mofii commented on src/multimeter/keysight_common.jl
> +end
add a return statement.

2022-06-02 01:25 UTC, longsnn commented on src/multimeter/keysight_common.jl
> +        instr::Instr{<:KeysightMultimeter}, # DMM Instrument
Thanks, I am working on the changes.

> With this design, how do you support doc-strings for different multimeter models? And how do external users add more DMM models? (which have other allowed ranges and resolution combinations from the model that we have)

I think we will have to create a unique get_voltage method for each model. What do you think?

> Did you notice that you changed the API? I made the three last input arguments named arguments on pupose. Please re-introduce that.

Could you please explain this more? The three last arguments still have names or am I missing something? 

> I'm not yet convinced that it's easier for the user to input `type`, `range`, and `plc` over `type`, `range` and `resolution`.

Using PLC instead of resolution allows the user the same capability while using a smaller list. Also, the different Keysight DMM models have relatively the same PLC set. Please let me know your decision after you talk it over with Quintin.

2022-06-02 01:25 UTC, longsnn commented on src/multimeter/keysight_common.jl
> +        instr::Instr{<:KeysightMultimeter}, # DMM Instrument
Thanks, I am working on the changes.

> With this design, how do you support doc-strings for different multimeter models? And how do external users add more DMM models? (which have other allowed ranges and resolution combinations from the model that we have)

I think we will have to create a unique get_voltage method for each model. What do you think?

> Did you notice that you changed the API? I made the three last input arguments named arguments on pupose. Please re-introduce that.

Could you please explain this more? The three last arguments still have names or am I missing something? 

> I'm not yet convinced that it's easier for the user to input `type`, `range`, and `plc` over `type`, `range` and `resolution`.

Using PLC instead of resolution allows the user the same capability while using a smaller list. Also, the different Keysight DMM models have relatively the same PLC set. Please let me know your decision after you talk it over with Quintin.

2022-06-09 01:44 UTC, closed without merging