Added SMU high priority commands
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #134
Opened 2022-06-16 01:37 UTC by longsnn

2022-06-16 07:54 UTC, mofii requested changes
Looks good.
See the comments within the code. They are all pretty minor requests.

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +enable_output(obj::Instr{<:AgilentSourceMeasureUnit}; chan = 1) = write(obj, ":OUTP$chan ON")
`channel` instead of `chan`

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +enable_output(obj::Instr{<:AgilentSourceMeasureUnit}; chan = 1) = write(obj, ":OUTP$chan ON")
Describe the `channel` parameter in the doc test

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +disable_output(obj::Instr{<:AgilentSourceMeasureUnit}; chan = 1) = write(obj, ":OUTP$chan OFF")
The last two comment goes for this function and most of the functions in this file as well.

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    set_output_current(obj::Instr{<:AgilentSourceMeasureUnit}, current::Current; chan = 1)
Write out `Unitful.Current` instead of `Current`

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +set_output_current(obj::Instr{<:AgilentSourceMeasureUnit}, current::Current; chan = 1) = write(obj, ":SOUR$chan:CURR $(raw(current))")
Previous comment goes here as well

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +set_output_voltage(obj::Instr{<:AgilentSourceMeasureUnit}, voltage::Voltage; chan = 1) = write(obj, ":SOUR$chan:VOLT $(raw(voltage))")
Write out `Unitful.Voltage`.

I'd to at some point to load all packages with `import Xxxx` instead of `using Xxx`.

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +verify_measurement_type(type) =  !(type in ["VOLT", "CURR", "RES"]) && error("Measurement type \"$type\" is not valid!\nIt's value must be \"VOLT\", \"CURR\", or \"RES\".")
Add unit tests for the helper functions

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function attach_type!(value, type)
It's a unit not a type

2022-06-16 07:54 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    if type == "CURR"
You can use `elseif` here to make the code quit testing if-statements faster.

2022-06-17 23:46 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +        - true | false (Default)
"If resistance is set true, the device enables voltage and current measurements as well. "
Is that correct? That's at least my recollection of what you told me.

2022-06-18 00:02 UTC, mofii requested changes
Looks good!
I had some very minor change requests. See the comments.

2022-06-18 00:02 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +        - Otherwise this can be an int: 1, 2, 3 .. to n
`- Valid values are positive integers 1 to N, where N is the number of channels on the device.`

2022-06-18 00:08 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +
We'll need a line here that converts the container (`mode`) from `Vector{String}` back to the base type (`String`).
`mode = mode[1]`

2022-06-28 07:58 UTC, mofii requested changes
We're getting close!
See the comments within the code.

2022-06-28 07:58 UTC, mofii commented on .tcp_instruments.yml
> +AgilentB2910BL: "10.1.10.33"
It looks like this device wasn't plugged into the correct port on the switch. It should be on the 10.1.30.0 network.

2022-06-28 07:58 UTC, mofii commented on src/TcpInstruments.jl
> +const NaN = 9.91e37
Don't overwrite a built-in language qualifier. I'm surprised that this compiles. 
Instead you could use `SMU_NAN`

2022-06-28 07:58 UTC, mofii commented on src/TcpInstruments.jl
> +export Oscilloscope, Multimeter, PowerSupply, WaveformGenerator, ImpedanceAnalyzer, SourceMeasureUnit
split into two line

2022-06-28 07:58 UTC, mofii commented on src/TcpInstruments.jl
> +export set_voltage_mode, set_voltage_output, set_voltage_limit
I'd like to add `get_source_mode()` as well.
For symmetry, add `set_source_mode()` which accepts "voltage" and "current" input arguments.
Delete `set_voltage_mode()` and `set_current_mode()`.

2022-06-28 07:58 UTC, mofii commented on src/TcpInstruments.jl
> +export set_measurement_range, set_measurement_time, start_measurement
Is `set_measurement_time()` the measurement sampling duration?
Using `_time()` sounds like the time of the day. 
Maybe `_duration()` is better.

2022-06-28 07:58 UTC, mofii commented on src/TcpInstruments.jl
> +export set_to_sweep_mode
What are the alternatives modes to `set_to_sweep_mode()`?

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
>  """
I assume this first string should be deleted?

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    write(obj, ":SENS$channel:FUNC:OFF:ALL")
Use descriptive function call instead.
Could be `_clear_measurement_mode()`

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    write(obj, ":SENS$channel:FUNC $mode")
Use descriptive function call instead.
Could be `_set_measurement_mode(instr, channel, mode)`

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function disable_autorange(obj::Instr{<:AgilentSourceMeasureUnit}; source="VOLT", channel = 1)
rm space (repeat for rest of file when present)

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    write(obj, ":FORM:ELEM:SENS VOLT,CURR,RES")
replace with descriptive function call

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    val = query(obj, ":FETCH:ARR? (@$channel)"; timeout = 0)
replace with descriptive function call

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    val = filter( x -> x/oneunit(x) != NaN, val)
What's `x/oneunit(x)` for?
Looks like you can use `filter!()` here

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    val = val[1] * V, val[2] * A, val[3] * R
Does the device always return three values? 
What if `val[3]` doesn't exist?

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    val = split(val, ",")
Move these four lines into a descriptive function call. `parse_smu_measurement()` or similar.

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +verify_range(range) = nothing
Which cases does this one catch?
Looks like it still needs to be implemented.

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +enable_output(obj::Instr{<:AgilentSourceMeasureUnit}; channel=1) = write(obj, ":OUTP$channel ON")
Add input parameter verification of `channel` in all these functions

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    write(obj, ":SOUR$channel:VOLT $(raw(voltage))")
Move this line to a single line function `_set_voltage_output(channel, voltage)` on the line just below this function.

Repeat the approach for all similar functions below.

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    spot_measurement(obj::Instr{<:AgilentSourceMeasureUnit}; channel=1)
What's the difference between `get_measurement()`, `spot_measurement()`, and `start_measurement()`?

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function attach_unit!(value, unit)
Move this function to right after the function where it's used.

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    verify_voltage(start)
`verify_start()`

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +        - "VOLT" (Default) | "CURR" | "RES"
Valid input parameter values throughout this file should be:
- "voltage"
- "current"
- "resistance"
- "default"
- "minimum"
- "maximum"
- "fixed" (I assume that's what "FIX" means?)
- "sweep" (for "SWE"?)
- "up"
- "down"

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +verify_current(current) = !(current isa Unitful.Current) && error("Current type be of Unitful.Current")
"Type of 'current' must be a Unitful.Current."

2022-06-28 07:58 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +verify_current(current) = !(current isa Unitful.Current) && error("Current type be of Unitful.Current")
Instead of:
```julia
verify_current(current::String) = verify_value_specifier(current)
verify_current(current) = !(current isa Unitful.Current) && error()
```

Could do:
```julia
verify_current(current::String) = verify_value_specifier(current)
verify_current(current::Unitful.Current) = nothing
verify_current(current) = error()
```

2022-06-28 23:01 UTC, longsnn commented on src/TcpInstruments.jl
> +export set_to_sweep_mode
I can change it to set_source_mode() for possible modes: "SWE", "LIST", and "FIX". Should I implement the relevent list mode functions as well such as set_list_start(), set_list(), and append_to_list()?

2022-06-28 23:18 UTC, longsnn commented on src/source_measure_unit/agilent_common.jl
> +    val = filter( x -> x/oneunit(x) != NaN, val)
x = x/oneunit(x) is to remove any unit connected to 'x' since 1 != 1u"V". Would ustrip(x) work better?

2022-06-28 23:22 UTC, longsnn commented on src/source_measure_unit/agilent_common.jl
> +    val = val[1] * V, val[2] * A, val[3] * R
According to the B2900 manual, yes. "If the measurement function is not enabled or no data exists, response returns
+9.910000E+37 (ASCII) or NaN (IEEE-754) which indicates “not a number”. " - pg. 4-28

2022-06-28 23:40 UTC, longsnn commented on src/source_measure_unit/agilent_common.jl
> +    spot_measurement(obj::Instr{<:AgilentSourceMeasureUnit}; channel=1)
I'll make it more clear in my next commit. 
start_measurement() will trigger the device to measure and store data on the device without returning any data. 
get_measurement() returns the last measured data from buffer.
spot_measurement() will initiate a measurement and return data in real time.

2022-06-28 23:42 UTC, longsnn commented on src/source_measure_unit/agilent_common.jl
> +verify_current(current) = !(current isa Unitful.Current) && error("Current type be of Unitful.Current")
That looks cleaner, thanks.

2022-06-29 18:28 UTC, longsnn commented on src/TcpInstruments.jl
> +export set_voltage_mode, set_voltage_output, set_voltage_limit
There's a small conflict.
Source output mode can be voltage or current
Source mode can be sweep, fixed, or list.
Would set_source() and set_source_mode() be better?

2022-07-07 00:47 UTC, longsnn commented on src/source_measure_unit/agilent_common.jl
> +    val  = f_query(obj, "MEAS:$measurement? (@$channel)"; timeout = 0)
Not needed. I have removed timeout=0 in most places so it defaults to timeout=0.5. Get_measurement requires longer than timeout=0.5 depending on number of points. Get_measurement timeout=2 currently.

2022-07-08 21:07 UTC, mofii requested changes
See the comments

2022-07-19 18:55 UTC, merged