Added SMU example to README.md
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #137
Opened 2022-07-20 19:00 UTC by longsnn

Example on how to start a voltage source sweep on SMU.

2022-07-21 19:42 UTC, mofii requested changes

2022-07-21 19:42 UTC, mofii commented on README.md
> +
remove empty lines

2022-07-21 19:42 UTC, mofii commented on README.md
> +Start a voltage source sweep and get sweep data.
The following example starts a voltage sweep and measures the current usage at each voltage level.

2022-07-21 19:42 UTC, mofii commented on README.md
> +set_source_mode(smu; source="voltage", mode="sweep")
Do we need to set `"voltage"` here when it was just done in `set_source()`?

I'm leaning towards merging `set_source()` and `set_srouce_mode()` in to one command. - Let's discuss later

2022-07-21 19:42 UTC, mofii commented on README.md
> +data = get_measurement(smu)
What's the exact output in this case when `set_measurement_mode` hasn't beed used?

2022-07-21 19:42 UTC, mofii commented on README.md
> +
Add an example for 
- setting the output voltage to a certain level.
- grabbing the current output

2022-07-21 19:55 UTC, longsnn commented on README.md
> +set_source_mode(smu; source="voltage", mode="sweep")
Combining works with me, it is just that separating them allows a little extra flexibility. 
For example:

There are two sources: voltage and current
There are three possible modes for the sources: fixed, sweep, and list

set_source - changes the source to voltage or current.
set_source_mode - changes that specific source's mode without changing to that source. Ex. You can change current source's mode without changing the source to current. 

To avoid this confusion, we can just merge the two functions so that changing source and source mode must happen same time.

2022-07-21 20:23 UTC, longsnn commented on README.md
> +data = get_measurement(smu)
get_measurement will always return voltage, current, resistance, and time. 
By default, only voltage, current, and time are active.
If a measurement is not active, the device will return "9.91e37" which means "NaN".

2022-07-25 23:41 UTC, longsnn commented on README.md
> +data = get_measurement(smu)
"9.91e37" is now replaced with `missing` which is plottable.

2022-10-27 19:12 UTC, mofii requested changes
This PR needs to be split into 2 maybe 4 PRs. My recommendation is to split into the following PRs:
- [x] Core SMU code updates (with a PR description of what the changes do)
- [ ] Unit tests updates - this could be included in the same PR as the previous PR.
- [ ] Docstring updates - this could be included in the same PR as the previous PS.
- [ ] Plotting updates - this definitely needs to be it's own PR 
- [ ] New updates: RecipesBase.jl has been depricated. I don't know if it works out of the box when loading Plots.jl or how to best load the recipes without loading Plots.jl. This PR would implement a solution for that 

As mentioned in the code comments, we shouldn't lode Plots.jl but instead use the same RecipesBase.jl framework as already used for the oscilloscope plotting.

2022-10-27 19:12 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function plot_all(data::SourceMeasureUnitData;)
Instead of custom plot functions use `@recipe` as is implemented in src/oscilloscope/recipes.jl

2022-10-27 19:12 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function plot_all(data::SourceMeasureUnitData;)
In other words, please move this code to `/src/source_measure_unit/recipes.jl` and convert both of these functions into one that accepts named input arguments and uses `@recipe`

2022-10-27 19:12 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +function plot_iv(data::SourceMeasureUnitData;)
Same comment as for `plot_all()`

2022-12-02 19:59 UTC, gita135 commented
> This PR needs to be split into 2 maybe 4 PRs. My recommendation is to split into the following PRs:
> 
> * [x]  Core SMU code updates (with a PR description of what the changes do)
> * [x]  Unit tests updates - this could be included in the same PR as the previous PR.
> * [x]  Docstring updates - this could be included in the same PR as the previous PS.
> * [ ]  Plotting updates - this definitely needs to be it's own PR
> * [x]  New updates: RecipesBase.jl has been depricated. I don't know if it works out of the box when loading Plots.jl or how to best load the recipes without loading Plots.jl. This PR would implement a solution for that
> 
> As mentioned in the code comments, we shouldn't lode Plots.jl but instead use the same RecipesBase.jl framework as already used for the oscilloscope plotting.

(1)SMU Core commands (2) unit test done in closed PR #134 (3) docstrings by #181 (5) no need to remove recipesbase.jl since lib was moved to plots.jl and was not deprecated (4)  plotting is being worked #177 . this PR can be closed

2022-12-02 23:09 UTC, mofii commented
Thanks!

2022-12-02 23:09 UTC, closed without merging