Refactoring Instr{} into per-group structs
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #175
Opened 2022-11-19 01:09 UTC by YoniEisipsSNN

This PR addresses JIRA ticket HWS-183 regarding refactor of `Instrument` to be an abstract supertype and have implementations of a `mutable struct` for each instrument type. This will allow for better dispatching and refactors for speedup in the future, i.e. `Oscilloscope` struct may now accommodate an `ScopeData` struct attribute allowing for data to be saved directly into the fields of an instrument's struct. This closes the first attempt PR #171

2022-12-01 22:42 UTC, mofii requested changes
See the code comments.
I think a block-diagram styled drawing of which types we have and how they relate could be useful for our discussion of this important change.

2022-12-02 18:15 UTC, YoniEisipsSNN commented on src/instrument.jl
> +abstract type Model end
Renaming `Instrument` to `AbstractInstrument`, as in HWS-202, should resolve this. `Model` could be changed to `AbstractModel` or `ModelName` for clarity, but as it stands currently it is a supertype for all possible types of physical lab instruments, such as `AgilentDSOX4024`, which is not an `Instrument` but only a `Model`. `Oscilloscope{AgilentDSOX4024A}` is an instrument of type `Oscilloscope` with an `OscilloscopeModel` of type `AgilentDSOX4024A`

2022-12-02 18:44 UTC, YoniEisipsSNN commented
Let me know if this diagram of the type structure in `TcpInstruments.jl` is helpful or accurate. I am eagerly awaiting your feedback on this PR.
![TcpTypeBlockDiagram](https://user-images.githubusercontent.com/110641283/205363711-3e6a6526-321b-452c-976b-55bb749b5043.png)

2022-12-02 19:21 UTC, mofii commented
Thanks @YoniEisipsSNN .
I'm still lacking an argument for what we gain by having the added complexity of two different abstract types?

For the drawing to be really useful, we should have two, one for the current situation in main, and one for what this PR is proposing.

2022-12-02 19:37 UTC, mofii commented
@YoniEisipsSNN I created a new branch based on the current `main` branch, it's called `instrument_type_refactor`. Let's make all PR's regarding the type system and new structs merge into that branch. Then we can do a thorough test of that branch before merging it to the main branch.

2022-12-14 18:46 UTC, mofii requested changes
Great, I'm looking forward to this!
See the comments within, I think the main point to change is to rename `Model` to `AbstractModel`.

2022-12-14 18:46 UTC, mofii commented on src/oscilloscope/AgilentDSOX1204G.jl
> +function set_impedance_50ohm(instr::Oscilloscope{T}; chan=1) where {T <: AgilentDSOX1204G}
Unrelated to this PR's change, but writing it here while I can remember:
It doesn't look like we need to define T here. I think this would be simpler:
```julia
function set_impedance_50ohm(instr::Oscilloscope{AgilentDSOX1204G}; chan=1) 
error("AgilentDSOX1204G impedance is fixed to 1 MΩ")
    return nothing
end
```

2022-12-14 18:46 UTC, mofii commented on src/oscilloscope/AgilentDSOX1204G.jl
> +function set_impedance_50ohm(instr::Oscilloscope{T}; chan=1) where {T <: AgilentDSOX1204G}
I love how simple it is to read 
```julia 
set_impedance_50ohm(instr::Oscilloscope{AgilentDSOX1204G})
```
Who remembers that `AgilentDSOX1204G` is an oscilloscope? It's a lot simpler to arrive at that conclusion over the previous:
```julia 
set_impedance_50ohm(instr::Instrument{AgilentDSOX1204G})
```

2022-12-14 18:49 UTC, mofii commented
@YoniEisipsSNN, I see you have another branch based on this branch.
I'll merge this PR and open issues for the comments I had on this PR.

2022-12-14 18:51 UTC, merged