HWS-192 Replace read() with read_with_timeout()
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #176
Opened 2022-11-21 18:34 UTC by YoniEisipsSNN

This PR should resolve Jira ticket 192. Changes in agilent_common.jl for both oscilloscopes and Impedance analyzers. Some minor spacing fixes.

2022-11-28 22:57 UTC, mofii commented
@YoniEisipsSNN, This one doesn't merge into `main`.
Is there a PR for the other branch that his PR merges to?

2022-11-28 22:59 UTC, mofii requested changes
Looks great. There were a lot more `read()`s than I was expecting!
Only comment is to increase the standard timeout value

2022-11-28 22:59 UTC, mofii commented on src/TcpInstruments.jl
> +const DEFAULT_TIMEOUT = 0.5
Let's make this 5 seconds

2022-11-29 21:32 UTC, mofii commented
@YoniEisipsSNN This PR has merge conflicts (probably from switching the base branch).
See also the comment of increasing the timeout from 0.5s to 5s.

2022-12-01 20:39 UTC, mofii requested changes
See the comments within the code.

2022-12-01 20:39 UTC, mofii commented on src/instrument.jl
>  function read_with_timeout(instr::AbstractInstrument, timeout_sec=2.8)
Update `timeout_sec=2.8` to 5 seconds

2022-12-01 20:39 UTC, mofii commented on src/TcpInstruments.jl
> +const DEFAULT_TIMEOUT = 5
There's no need to define a global for this, the function `read_with_timeout()` already has a standard value for the default time out.

2022-12-01 20:39 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    volt_ac = parse(Float64, read_with_timeout(ia, DEFAULT_TIMEOUT)) * u"V"
Remove all cases of `DEFAULT_TIMEOUT` and rely on the functions own default value.

2022-12-02 19:29 UTC, mofii commented
Looks great @gita135 !
I just saw we're changing the read() for the impedance analyzer as well. That means we took the timeout down from infinity to 5 seconds. I worry if there are any corner cases for that old instrument where 5 seconds is not enough.
Long story short, I changed my mind on the standard timeout value -> let's increase it to 10 seconds.

2022-12-02 19:37 UTC, gita135 commented
> Looks great @gita135 ! I just saw we're changing the read() for the impedance analyzer as well. That means we took the timeout down from infinity to 5 seconds. I worry if there are any corner cases for that old instrument where 5 seconds is not enough. Long story short, I changed my mind on the standard timeout value -> let's increase it to 10 seconds.

Done 👍

2022-12-02 19:39 UTC, mofii approved these changes
Great! 👍

2022-12-02 19:40 UTC, merged