HWS-198: show() command for SMU
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #182
Opened 2022-12-01 22:13 UTC by gita135

Made ```show()``` function for SMU. Added in struct for SMUInfo to have same   ```show()``` layout as scope

2022-12-01 22:21 UTC, mofii commented
Hi @gita135 , can I get you to request me as a reviewer when you submit a new PR? Thanks!

2022-12-01 22:40 UTC, mofii requested changes
See the comments within the code.

2022-12-01 22:40 UTC, mofii commented on src/source_measure_unit/types.jl
> +
It looks like the above docstring is no longer a valid docstring since it's not connected to a struct definition or a function?

2022-12-01 22:40 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    smuInfo = SourceMeasureUnitInfo(channel, get_source(obj), get_source_mode(obj), _get_voltage_step(obj, channel), _get_voltage_span(obj, channel))
Use snake case for variable names

2022-12-01 22:40 UTC, mofii commented on src/source_measure_unit/agilent_common.jl
> +    smuInfo = SourceMeasureUnitInfo(channel, get_source(obj), get_source_mode(obj), _get_voltage_step(obj, channel), _get_voltage_span(obj, channel))
The 4 added getter function calls are going to slow down `get_measurement` significantly.
What's the motivation for this change? We have something similar for the oscilloscope so I can see where the idea came from, but as shown above, there is no free lunch.
At the very least, this change should go into a separate PR - as this PR's purpose is to just add a `show()` command.

2022-12-01 22:40 UTC, mofii commented on src/source_measure_unit/types.jl
> +  voltageStepSize::Float64 #If in sweep mode
If this struct is added, it should use Unitful units.
See the above question on what the motivation for the change is.

2022-12-02 01:04 UTC, gita135 commented
My initial thoughts for adding in the ```SourceMeasureUnit``` struct was what settings/information would be useful for the user (like the scope). I removed the struct and corresponding ```show()``` functions so no slowdown in a ```get_measurement()``` call. if any of the info in the struct would be useful, I can make a separate PR for it , but we can discuss in meeting (?)

2022-12-02 18:45 UTC, mofii requested changes
Looks good!
Last request, could you attach what the output looks like for a single `SourceMeasureUnitData` and a vector of `SourceMeasureUnitData`?

2022-12-06 01:29 UTC, gita135 commented
> Looks good! Last request, could you attach what the output looks like for a single `SourceMeasureUnitData` and a vector of `SourceMeasureUnitData`?

![Screen Shot 2022-12-05 at 5 25 38 PM](https://user-images.githubusercontent.com/105512097/205785895-5c9efa99-f06f-41cd-80be-bd9455b789f6.png)
our smu only has 1 channel

2022-12-09 21:26 UTC, mofii requested changes

2022-12-09 21:26 UTC, mofii commented on src/source_measure_unit/types.jl
> +      println(io, "Channel #$idx")
It looks to me like the original implementation was better?
What if data was measured on channel 2 and 3, then it would now print channel 1 and 2, no?

That said, we only have one channel on our SMU, so why do we have this code at all?

2022-12-13 01:21 UTC, mofii approved these changes
👍

2022-12-13 01:22 UTC, merged