LAB-230-implement-settings-struct
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #199
Opened 2022-12-17 00:06 UTC by YoniEisipsSNN

Temporarily pointing to Lab-229 as base for ease of review.

2022-12-21 06:57 UTC, mofii requested changes
I'd like the settings structs to be immutable in order to make it harder for the users to manually change settings which then don't reflect the state of the instruments. 
The immutable structs can then internally be updated using the Accessors.jl package.
This could look something like this (untested):

```julia
function set_address!(instr::AbstractInstrument, address::String) 
 tcp = instr.tcp
 new_tcp = @set tcp.address = address
 instr.tcp = new_tcp
 return nothing
end
```

2022-12-21 06:57 UTC, mofii commented on src/impedance_analyzer/types.jl
> +        false,
```julia
 connected = false
 ImpedanceAnalyzer{model}(
        TCPInfo(address, TCPSocket()),
        ImpedanceAnalyzerSettings(),
        connected,
 )
```

2022-12-21 06:57 UTC, mofii commented on src/impedance_analyzer/types.jl
> +mutable struct ImpedanceAnalyzerSettings <: AbstractSettings
I'd like to make the settings struct immutable in order to make it harder for the users to manually change settings

2022-12-21 06:57 UTC, mofii commented on src/power_supply/types.jl
> +mutable struct PowerSupplySettings <: AbstractSettings
immutable.
What are we gaining from having an AbstractSettings type?

2022-12-21 06:57 UTC, mofii commented on src/source_measure_unit/types.jl
> +mutable struct SourceMeasureUnitSettings <: AbstractSettings
immutable

2022-12-21 06:57 UTC, mofii commented on src/waveform_generator/types.jl
> +mutable struct WaveformGeneratorSettings <: AbstractSettings
immutable

2022-12-21 06:57 UTC, mofii commented on src/instrument.jl
>  mutable struct TCPInfo
immutable

2022-12-21 06:57 UTC, mofii commented on src/instrument.jl
>  mutable struct TCPInfo
The "connected" field should also go into this struct.

2022-12-21 06:57 UTC, mofii commented on src/instrument.jl
>      info::TCPInfo
I think "info" is too vague a field name.
"tcp" could work.
Then it reads as"
```julia
instr.tcp.connected
instr.tcp.socket
instr.tcp.address
```

2022-12-21 06:57 UTC, mofii commented on src/instrument.jl
>  get_address(i::AbstractInstrument) = i.info.address
"i" is often a counting index variable. 
"instr" is not super elegant but I like it better as an abbreviation for instrument than "i". Also open for other proposals!

2022-12-22 00:39 UTC, gita135 commented on src/power_supply/types.jl
> +mutable struct PowerSupplySettings <: AbstractSettings
@mofii  This is something I am unsure of, I can run it by Yoni once he returns 👍🏽

2023-01-04 00:29 UTC, mofii commented
@gita135 
Let's keep commits that are related to the TCPInfo struct in the LAB-229 branch and PR. From a brief overview, it looks like that would be the following commits:
- Added set_tcp_connected!() calls to connect!() and close!()
- Implemented set_tcp_connected!()
- Fixed connected var in create_instrument()
- Added connected field to TCPInfo struct
- Added connected var to all uses of TcpInfo in create_instrument()
- Added connected var call to TcpInfo for instr
- Added Accessors Package
- Added connected var to create_instrument() call
- Refactored set_socket() and set_address() to use Accessors
- Added ! to set_address() and set_socket()

Please cherry pick the commits such they become part of LAB-229 and drop the commits here using `git rebase -i`.

I think the Accossors.jl code gets to be too clunky for now. Let's make the structs mutable and keep the code clean. We might at a later time be able to make a cleaner implementation of immutable structs Accessors.jl if needed.

2023-01-13 22:00 UTC, mofii commented
Hi @YoniEisipsSNN and @gita135, 
This one has a lot of merge conflicts. Would you mind rebasing it and solving the merge conflicts?
Thanks!

2023-01-13 22:00 UTC, mofii requested changes
Needs a rebase

2023-01-27 20:47 UTC, mofii approved these changes
🥳

2023-01-27 20:47 UTC, merged