LAB-222: Scope Unit Tests
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #201
Opened 2022-12-20 20:32 UTC by gita135

"Oscilloscope: Script with a full set of unit tests, testing all functions for the device to be run manually before each release"

2022-12-21 00:59 UTC, gita135 commented
@mofii If you could give me any feedback on the tests ive written so far/ any additional test recommendations that would be greaat thank you

2022-12-23 18:51 UTC, mofii requested changes
Lot's of good stuff here!
I was a little confused about a couple of the tests - see the comments.
This was also useful for seeing parts of the API that we rarely use in action. I now have some things I'd like to change in the scope API, I'll open issues for those.

The real meat of this addition will come in the last section where the high-level tests are. They are also ones that will take the longest to define and program.

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +    @test_throws MethodError TcpInstruments.set_data_transfer_byte_order(scope, "LSBF")
Why does it throw a MethodError?
That doesn't sound like the behavior we'd like to see?

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +    @test_throws UndefVarError TcpInstruments.set_data_transfer_byte_order(scope, least_significant_first)
Same for this line, why are we seeing an UndefVarError and why are we testing for it?
If we test for a certain behavior we're saying this is the behavior we want to see and if that changes the tests will fail. as you can hear, I'm confused about the intend of the test.

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +@testset "waveform info" begin
These tests are unnecessary, as they are testing the types of the fields in the struct ScopeInfo. It's an immutable struct with well-defined types, so they can't change.

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
>  @info "Successfully connected $(scope.model) at $(scope.address)"
You need to test for a successful connection before printing that it was successful.

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +@testset "get data"  begin
There's also:
- get_data(scope)
- get_data(scope, 1) # (you already had this one)
- get_data(scope, 2)
- get_data(scope, [1,2])


Next step is to agree on a test signal to use from the scope and then compare the recorded data to the expected test-signal.

Then we can change the number of data points in the acquisition and test that this really impacts the measured data.

We can change the bit resolution and change that this really impacts the returned data.

We can make a for-loop of 10k get_data(scope, 1) and get_data(scope, [1,2]) and make they don't fail.

2022-12-23 18:51 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +@testset "get data"  begin
For this to really work, we need to be able to remotely set more settings on the scope, such as:
- time scale (t/div and t-offset)
- voltage scale (V/div and v-offset)
- Trigger mode and level

2022-12-23 19:00 UTC, gita135 commented on test/scope/agilent_dsox4034a.jl
> +@testset "get data"  begin
Ok, sounds good! I knew this needed the most robust testing but was unsure on which route to take. thank you

2023-01-12 23:34 UTC, gita135 commented on test/scope/agilent_dsox4034a.jl
> +    @test_throws MethodError TcpInstruments.set_data_transfer_byte_order(scope, "LSBF")
If there is an invalid input -- a string instead of a symbol. But these functions are internal so I agree with these being necessary tests.

2023-01-13 01:23 UTC, gita135 commented on test/scope/agilent_dsox4034a.jl
> +@testset "get data"  begin
@mofii  Ok! Those commands are in their separate PRs. Would you also recommend having peak to peak voltage and frequency of the signal?

2023-01-13 21:38 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +@testset "get data"  begin
@gita135 
Are those metrics easy to grab?
If so then we can make a new ticket for that.
For now, can you convert this draft PR to a full PR, and get it merged without the higher level functions. We'll add those later in a separate PR.

2023-01-27 20:40 UTC, mofii approved these changes
Yup, let's get it in!

2023-01-27 20:41 UTC, merged