Lab-231, 232, 233: Refactor read(instrument) for num_bytes
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #216
Opened 2023-01-10 22:23 UTC by gita135

-patch read(instr) to support reading num_bytes
-patch read_with_timout(instr) to support reading only num_bytes
-change all raw socket reads to use new read(instr, num_bytes)

Addresses issue #215

2023-01-10 23:58 UTC, mofii requested changes
Looking good! See the change requests within.

2023-01-10 23:58 UTC, mofii commented on src/instrument.jl
> +function read(instr::AbstractInstrument; num_bytes=nothing)
```julia
read(instr::AbstractInstrument; num_bytes::Integer=0)
```

2023-01-10 23:58 UTC, mofii commented on src/instrument.jl
> +    if isnothing(num_bytes)
```julia
function read(instr::AbstractInstrument; num_bytes=nothing)
    if isnothing(num_bytes)
        !instr.connected && error("Instrument is not connected, cannot read from it!")
        return rstrip(readline(instr.sock), ['\r', '\n'])
    else 
        return read(instr.sock, num_bytes)
    end
end
```
to
```julia
function read(instr::AbstractInstrument; num_bytes::Integer=0)
    verify_is_connected(instr)
    if num_bytes == 0
        retval = rstrip(readline(instr.sock), ['\r', '\n'])
    else
        retval = read(instr.sock, num_bytes)
    end
    return retval
end

verify_is_connected(instr) = !is_connected(instr) && error("Instrument is not connected, cannot read from it!")

```

2023-01-10 23:58 UTC, mofii commented on src/instrument.jl
> +    return timeout == 0 ? read(instr) : read_with_timeout(instr, timeout_sec=timeout)
We unify whether we use `timeout` or `timeout_sec`.
I think `timeout` is best and should be used everywhere, including in `read_with_timeout()`

2023-01-10 23:58 UTC, mofii commented on src/instrument.jl
> +function read_with_timeout(instr::AbstractInstrument; number_bytes=nothing, timeout_sec=5)
```julia
read_with_timeout(instr::AbstractInstrument; number_bytes=nothing, timeout_sec=5)
```
to
```julia
read_with_timeout(instr::AbstractInstrument; num_bytes::Integer=0, timeout=5)
```

2023-01-10 23:58 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_description_uint8 = read_with_timeout(scope, number_bytes = num_header_description_bytes)
Remove spaces around last equal sign.

2023-01-10 23:58 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_block_uint8 = read_with_timeout(scope, number_bytes = header_block_length)
Remove spaces around last equal sign

2023-01-10 23:58 UTC, mofii commented on src/instrument.jl
> +function read_with_timeout(instr::AbstractInstrument; number_bytes=nothing, timeout_sec=5)
Notice the `number_bytes` to `num_bytes` change to keep it the same as in `read()`

2023-01-11 06:15 UTC, mofii requested changes
Even closer!
See the tiny comments within the code.

2023-01-11 06:15 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_description_uint8=read_with_timeout(scope, number_bytes = num_header_description_bytes)
It's around the second equal sign the space needed to be removed. It's when using assignment to a named parameter that there's no white space around the equal sign.
That's as illustrated in [this section](https://github.com/invenia/BlueStyle#keyword-arguments) in the blue style

2023-01-11 06:15 UTC, mofii commented on src/instrument.jl
> +    return timeout_function(f, timeout)
You should be able to just call:
```julia
f() = read(instr; num_bytes)
```

2023-01-11 06:15 UTC, mofii commented on src/instrument.jl
> +    return timeout_function(f, timeout)
I think `timeout()` is cleaner than `timeout_function()`

2023-01-11 06:55 UTC, mofii commented on src/instrument.jl
> +    return timeout_function(f, timeout)
Ahh, I now see the problem. `timeout` is defined to be a parameter name. 
Let's change the parameter name `timeout` to `max_duration`.

2023-01-11 18:33 UTC, gita135 commented on src/instrument.jl
> +    return timeout_function(f, timeout)
Paramter name in `read_with_timeout()` only or all functions that use a timeout val? `query(), f_query(), i_query()`?``

2023-01-13 21:50 UTC, mofii requested changes
Small improvements. 
See the comments within the code

2023-01-13 21:50 UTC, mofii commented on src/instrument.jl
> +        retval = read(instr.sock, num_bytes)
should we not call `rstrip` here as well?

2023-01-13 21:50 UTC, mofii commented on src/instrument.jl
> +    return timeout == 0 ? read(instr) : read_with_timeout(instr, timeout=timeout)
````julia
read_with_timeout(instr; timeout)
```

2023-01-13 21:50 UTC, mofii commented on src/oscilloscope/agilent_common.jl
>      num_data_bytes = get_num_data_bytes(scope)
`num_data_bytes` -> `num_bytes`

2023-01-13 21:50 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    data = read_with_timeout(scope, num_bytes=num_data_bytes)
```julia
data = read_with_timeout(scope; num_bytes)
```

2023-01-13 21:50 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    data = reinterpret(UInt16, read_with_timeout(scope, num_bytes=num_data_bytes))
```julia
data = reinterpret(UInt16, read_with_timeout(scope; num_bytes))
```

2023-01-13 21:50 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_description_uint8 = read_with_timeout(scope, num_bytes=num_header_description_bytes)
```julia
read_with_timeout(scope; num_bytes=num_header_description_bytes)
```

2023-01-13 21:50 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_block_uint8 = read_with_timeout(scope, num_bytes=header_block_length)
```julia
read_with_timeout(scope; ...
```

2023-01-14 01:18 UTC, mofii requested changes
Close!

2023-01-14 01:18 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_description_uint8 = read_with_timeout(scope; num_header_description_bytes)
Here you can't do it. It's only when the variable name is the same as the named parameter that you don't have to say `f(x; a=a`) but can do `f(x, a)`. If the variable name is `b` you have to do `f(x, a=b)`

2023-01-14 01:18 UTC, mofii commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
How come you here want to do `rstrip()` without specifying the characters as in line 230?
Shouldn't the two cases be the same?

2023-01-14 01:18 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    header_description_uint8 = read_with_timeout(scope; num_bytes=num_header_description_bytes)
I read your PRs commit per commit.
When you're fixing something from a previous commit, please merge those two commits (git calls it `squash` when rebasing).

2023-01-17 21:04 UTC, gita135 commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
Actually do not want to call either `rstrip()` or `readline()`  `rstrip()` returns substring and removes any trailing characters (specified by the chars like newline char etc)  and `readline()` reads whole line, not specified # of bytes. Because since we are specifying the number of bytes in `read()`, these 2 functions are not necessary.

2023-01-20 21:45 UTC, mofii commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
Could this under any circumstances cause us to get out of sync with the scope?
What if we read 8 bytes/chars and leave a '\r\n' in the buffer. Then next time we call `readline()` will it then only read the '\r\n' and not the following data?

2023-01-20 22:01 UTC, gita135 commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
I could add a call to `clear_buffer()` after @mofii

2023-01-20 22:02 UTC, mofii commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
OK, then let's do that

2023-01-27 17:48 UTC, gita135 commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
Actually, in the case of only reading a specified number of bytes, you wouldn't want to clear the buffer. We use read(scope, num_bytes) in get_data_header() for ex to only get the first 2 bytes before reading the rest of the data. If we clear it, then we would lose all the actual data that we want to read.

2023-01-27 20:43 UTC, mofii commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
@gita135 What's your recommendation? Should we merge it as-is?

2023-01-27 20:53 UTC, mofii commented
@deepaksnn is this ready to go?

2023-01-30 19:23 UTC, gita135 commented on src/instrument.jl
> +        retval = rstrip(read(instr.sock, num_bytes))
yes good to go

2023-01-30 20:55 UTC, mofii approved these changes

2023-01-30 20:57 UTC, merged