LAB-238, LAB-239: Set and get trigger [scope]
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #218
Opened 2023-01-12 23:09 UTC by gita135

Implemented `set_trigger(scope::Instrument{<:AgilentScope}; level::Voltage, mode::Symbol, edge::Symbol)` and `get_trigger(scope::Instrument{<:AgilentScope})` and their required helper functions
- `set_trigger_mode()`
- `get_trigger_mode()`
- `set_trigger_level()`
- `get_trigger_level()`
- `set_edge_type()`
- `get_edge_type()`

2023-01-13 19:43 UTC, mofii requested changes
Very nice, happy to see this moving along!
See the comments within the code.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return query(scope, "TRIGGER:LEVEL?")
What does the returned string look like?
Is it a voltage level? Then we should parse it as a voltage.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +- `String`: trigger mode
We should document here what the expected return values are (at least if there are not too possible values)

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +Sets trigger mode to either EDGE, GLITch, PATTern, TV, DELay, EBURst, OR, RUNT, SHOLd,
Let's convert this list into a human readable list with fully spelled out words.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +set_trigger_mode(scope::Instrument{<:AgilentScope}, ::Val{:delay}) = write(scope, "TRIGGER:MODE DEL") # doesn't work for both models
What characterizes which model it works on?
If we can pinpoint it we can the dispatching by traits / the type system.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +set_trigger_mode(scope::Instrument{<:AgilentScope}, ::Val{:edge}) = write(scope, "TRIGGER:MODE EDGE")
Good idea to use dispatching to solve this!

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +set_trigger_mode(scope::Instrument{<:AgilentScope}, mode::Symbol) = set_trigger_mode(scope, Val(mode))
I think our users find symbols intimidating. They've never encountered them before in other programming languages, so let's use strings instead. 
You can convert a string to a symbol by calling `Symbol(<string>)`.
Here it might be useful to call:
```julia
Val(Symbol(lowercase(<string>)))
```

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +set_trigger_mode(scope::Instrument{<:AgilentScope}, mode::Symbol) = set_trigger_mode(scope, Val(mode))
Let's verify in this function whether or not the scope supports the trigger mode and exit gracefully if it does not.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    write(scope, "TRIGGER:LEVEL $level")
Have you tested this?
I would expect there to be a `Float64(uconvert(V, level))` here?

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +- `String`: edge type
It would be nice with a list of the expected return values.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +set_edge_type(scope::Instrument{<:AgilentScope}, edge_type::Symbol) = set_edge_type(scope, Val(edge_type))
The same comment as for the other function, let's expose strings instead of symbols to the user.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    if get_trigger_mode(scope) == "EDGE"
Why do we have a special case for "EDGE"?
It's not good for the compiler that it can't predict how many return parameters this function will return. That means we can't precompile the code.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +- `mode::Symbol`: trigger mode
String instead of symbol

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        return (get_trigger_mode(scope), get_trigger_level(scope), get_edge_type(scope))
Depending on what the returned strings look like for these three functions, we should parse them before returning them to the user. 
The returned values should look just like the expected input in `set_trigger()`.

2023-01-13 19:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        return (get_trigger_mode(scope), get_trigger_level(scope), get_edge_type(scope))
I'm also considering whether we shold here return a small and easy readable struct instead of a tuple.
What are your thoughts?

2023-01-13 19:53 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +    if get_trigger_mode(scope) == "EDGE"
For `EDGE` trigger can either be of type `positive`, `negative`, `either` or `alternative`. For other trigger modes such as `PATTERN`, this may not be applicable, from my understanding.

2023-01-13 20:23 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +        return (get_trigger_mode(scope), get_trigger_level(scope), get_edge_type(scope))
I was thinking that too! Along with a `show()` for it. will make it much easier for user to read 👍🏽

2023-01-13 20:24 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +    if get_trigger_mode(scope) == "EDGE"
If we use a struct, then tthis would no longer be an issue

2023-01-17 02:09 UTC, gita135 commented
Implemented `get_mode()` and `set_mode()` in both `set_trigger()` and `get_trigger()` for `NORMAL` mode or `AUTO` mode. Also got rid of unncessary `set_trigger_mode()` functions since not used (said in meeting)

2023-01-27 20:49 UTC, mofii approved these changes
👍

2023-01-27 20:49 UTC, mofii commented
@gita135 Can I get you to rebase this branch on `main` and fix the merge conflicts?

2023-01-30 19:46 UTC, gita135 commented
> @gita135 Can I get you to rebase this branch on `main` and fix the merge conflicts?

done 👍

2023-01-30 20:52 UTC, mofii requested changes
Just a very small change request

2023-01-30 20:52 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +- `String`: trigger mode
I don't see this comment as being resolved for `get_trigger_mode()`?
What I meant was, what are the actual strings that this function returns?

2023-01-30 20:52 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return parse(Float64,query(scope, "TRIGGER:LEVEL?")) *u"V"
```julia
return parse(Float64,query(scope, "TRIGGER:LEVEL?")) *u"V"
```
->
```julia
return parse(Float64,query(scope, "TRIGGER:LEVEL?")) * V
```

2023-01-31 00:29 UTC, mofii commented
@gita135 Can I get you to request @deepaksnn as a reviewer first?

2023-01-31 00:30 UTC, gita135 commented
> @gita135 Can I get you to request @deepaksnn as a reviewer first?

👍🏽

2023-01-31 01:03 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +- `String`: trigger mode
Somehow missed this,  now is resolved

2023-01-31 17:52 UTC, deepaksnn commented
Looks good. 👍

2023-02-03 00:50 UTC, gita135 commented
@mofii  I am unable to re-reqest you, but this is ready for review 👍

2023-02-03 06:09 UTC, mofii requested changes
Besides the small change requests, I'd like the functions reorganized into the order in which they are called/used.

2023-02-03 06:09 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    set_trigger_level(scope, level)
Add input param verification.

2023-02-03 06:09 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +function get_trigger(scope::Instrument{<:AgilentScope})
Input param verification

2023-02-07 19:58 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +Sets edge type (slop) to either POSITIVE, NEGATIVE, EITH (either), Alt(alternative)
alternative -> alternate

2023-02-07 19:58 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +set_edge_type(scope::Instrument{<:AgilentScope}, ::Val{:alternative}) = write(scope, "TRIGGER:EDGE:SLOPE ALT")
alternative -> alternate

2023-02-07 19:59 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +    if edge_type ∈ ["POSITIVE", "NEGATIVE", "EITHER", "ALTERNATIVE"]
ALTERNATIVE -> ALTERNATE

2023-02-07 20:00 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +    edge_type_dic = Dict("POS" => "POSITIVE", "NEG" => "NEGATIVE", "EITH" => "EITHER", "ALT" => "ALTERNATIVE")
ALTERNATIVE -> ALTERNATE

2023-02-07 20:01 UTC, deepaksnn commented on test/scope/agilent_dsox4034a.jl
> +    TcpInstruments.set_edge_type(scope, "ALTERNATIVE")
ALTERNATIVE -> ALTERNATE

2023-02-07 20:13 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +    verify_channels(get_valid_channels(scope), channels)
Do we need this? We are verifying same thing twice!

2023-02-07 20:21 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +    verify_channels(get_valid_channels(scope), channels)
I believe so because we are dispatching on it --  can be called by `get_voltage_axis(scope, [1,2])` `get_voltage_axis(scope)` `get_voltage_axis(scope, 3)` therefore channels need to be verified  @deepaksnn

2023-02-07 20:39 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +    verify_channels(get_valid_channels(scope), channels)
Oh, I see what you mean now. Yes, the channel verification in only `get_voltage_axis(scope, channel::Integer)` makes the most sense.

2023-02-09 19:00 UTC, deepaksnn approved these changes
Looks Good 👍

2023-02-10 20:49 UTC, mofii approved these changes
👍

2023-02-10 20:51 UTC, merged