LAB-237: Implement get_voltage_scale()
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #219
Opened 2023-01-13 00:39 UTC by gita135

Implemented `get_voltage_scale()` and dispatchedd for 1 channel, all , or select ie [1,2]

2023-01-13 19:14 UTC, mofii requested changes
This get's the voltage per division parameter, but there's also the voltage offset, in other words where vertically on the screen 0V is located. I don't know what they call it in the manual?

2023-01-13 19:14 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +get_voltage_scale(scope::Instrument{<:AgilentScope}) = Tuple(uparse(query(scope, "CHANnel$ch:SCALe?") * "V") for ch in get_valid_channels(scope))
I find it too long for the short function definition syntax (The whole thing should comfortably fit on one line). Expand into the long form syntax and use the `_get_voltage_scale(scope, channel)` function.

2023-01-13 19:14 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +get_voltage_scale(scope::Instrument{<:AgilentScope}) = Tuple(uparse(query(scope, "CHANnel$ch:SCALe?") * "V") for ch in get_valid_channels(scope))
Let's keep it as `tuple()` instead of `Tuple()`

2023-01-13 19:14 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return tuple(uparse(query(scope, "CHANnel$ch:SCALe?") * "V"))
What is the `tuple()` call needed for?

2023-01-13 19:34 UTC, gita135 commented
> This get's the voltage per division parameter, but there's also the voltage offset, in other words where vertically on the screen 0V is located. I don't know what they call it in the manual?

Ok! Should this be returned as a tuple or union of the 2 values per channel

2023-01-13 19:55 UTC, gita135 commented
> This get's the voltage per division parameter, but there's also the voltage offset, in other words where vertically on the screen 0V is located. I don't know what they call it in the manual?

Ok got it. Should I return this as a tuple?

2023-01-13 22:27 UTC, mofii commented
Let's switch to a named tuple.

2023-01-27 20:29 UTC, mofii commented
@gita135 What does the returned output loek like when running this function?
Say for `get_voltage_scale(scope, [1,2])` ?

2023-01-27 21:17 UTC, gita135 commented
> @gita135 What does the returned output look like when running this function? Say for `get_voltage_scale(scope, [1,3])` ?
@mofii 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/105512097/215202412-08291d91-b0a0-4e03-b4bf-1f6908136ae6.png)

2023-01-27 21:27 UTC, mofii commented
Thanks. That means it's difficult for the user to keep track of what refers to what. For instance:
```julia
volt_axis = get_votage_scale(scope, [1,3])
volt_axis[2]
```
will output channel 3.

I think we should add what the channel index is to each named tuple.

```julia
julia> volt_axis = [(;channel=1, scale=200, offset=-143.8), (;channel=3,scale=5, offset=0)]
2-element Vector{NamedTuple{(:channel, :scale, :offset)}}:
 (channel = 1, scale = 200, offset = -143.8)
 (channel = 3, scale = 5, offset = 0)

julia> volt_axis[1]
(channel = 1, scale = 200, offset = -143.8)

julia> volt_axis[2]
(channel = 3, scale = 5, offset = 0)
```

2023-01-27 21:28 UTC, mofii requested changes
See the top-level comments

2023-01-28 01:11 UTC, gita135 commented
> Thanks. That means it's difficult for the user to keep track of what refers to what. For instance:
> 
> ```julia
> volt_axis = get_votage_scale(scope, [1,3])
> volt_axis[2]
> ```
> 
> will output channel 3.
> 
> I think we should add what the channel index is to each named tuple.
> 
> ```julia
> julia> volt_axis = [(;channel=1, scale=200, offset=-143.8), (;channel=3,scale=5, offset=0)]
> 2-element Vector{NamedTuple{(:channel, :scale, :offset)}}:
>  (channel = 1, scale = 200, offset = -143.8)
>  (channel = 3, scale = 5, offset = 0)
> 
> julia> volt_axis[1]
> (channel = 1, scale = 200, offset = -143.8)
> 
> julia> volt_axis[2]
> (channel = 3, scale = 5, offset = 0)
> ```

![Screen Shot 2023-01-27 at 5 11 10 PM](https://user-images.githubusercontent.com/105512097/215233376-acd9c0d9-f732-43c8-8eae-a0c296ab66ac.png)

2023-01-30 21:17 UTC, mofii requested changes
Very small change request

2023-01-30 21:17 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return (scale=_get_voltage_scale(scope, channel), offset=_get_voltage_offset(scope, channel))
In the interest of getting similar output for all three versions of this function, lets use your helper function here as well:
```julia
return _voltage_scale_tuple(scope, channel)
```

2023-01-30 21:17 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        error("Channel $channel is offline, voltage scale cannot be read")
```julia
if !(channel in get_valid_channels(scope))
```

2023-01-31 17:57 UTC, deepaksnn commented
Looks good 👍

2023-02-02 21:35 UTC, mofii requested changes
A pretty small refactor. See comments within

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    end
Wrap in function `verify_channels()`

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +function get_voltage_scale(scope::Instrument{<:AgilentScope}, channels::Vector{Int})
Rename to `get_voltage_axis()`

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +function get_voltage_scale(scope::Instrument{<:AgilentScope}, channel::Int)
`get_voltage_axis()`

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    end
Wrap in `verify_channel()`

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return _voltage_scale_tuple(scope, channel)
`_get_voltage_axis()`

2023-02-02 21:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +_voltage_scale_tuple(scope, channel) = (channel=channel, scale=_get_voltage_scale(scope, channel), offset=_get_voltage_offset(scope, channel))
Remove this function and put the tuple wrapping into `_get_voltage_scale()` and rename it to `_get_voltage_axis()`

2023-02-02 21:35 UTC, mofii commented on src/TcpInstruments.jl
> +export get_voltage_scale
`export get_voltage_axis`

2023-02-03 00:25 UTC, mofii commented
Hi @gita135 , 
It looks like this is ready for another review, or?

2023-02-03 00:27 UTC, gita135 commented
> Hi @gita135 , It looks like this is ready for another review, or?

yes 👍

2023-02-03 00:35 UTC, mofii requested changes
A very tiny comment! And mostly because I made a mistake in the last review.

2023-02-03 00:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +- `Vector{NamedTuple{(:a, :b), Tuple{Int64, Int64}}}`: voltage scale(s) and offset(s) from the scope
# Returns
A NamedTuple per channel with the fields:
- channel
- scale (Voltage per division)
- offset (Voltage offset)

2023-02-03 00:35 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    return (channel=channel, scale=_get_voltage_axis(scope, channel), offset=_get_voltage_offset(scope, channel))
My apologies @gita135 , I told you to rename this function, but I was too quick, this lower level function doesn't make sense to rename. Let's keep it at what you had before:  `_get_voltage_scale()`.

2023-02-03 00:52 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +    return (channel=channel, scale=_get_voltage_axis(scope, channel), offset=_get_voltage_offset(scope, channel))
Ok!

2023-02-03 05:41 UTC, mofii approved these changes
🎉

2023-02-03 05:42 UTC, merged