LAB-235: Add function: (get_) set_time_scale(scope; time_per_div, time_offset)
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #222
Opened 2023-01-17 23:07 UTC by gita135

Implemented `get_time_scale(scope::Instrument{<:AgilentScope})` and `set_time_scale(scope::Instrument{<:AgilentScope}; time_per_div::Unitful.Time, time_offset::Unitful.Time)`

2023-01-20 21:41 UTC, mofii requested changes
See the comments within

2023-01-20 21:41 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    if time_per_div < 2u"ns" || time_per_div > 50u"s"
Put this into a helper function that returns nothing but errors when not verified:
```julia
verify_time_per_div()
```

2023-01-20 21:41 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    elseif time_offset < -500u"s" || time_offset > 500u"s"
Put this into a helper function that returns nothing but errors when not verified:
```julia
verify_time_offset()
```

2023-01-20 21:41 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        if typeof(time_per_div) in (typeof(1u"μs"), typeof(1.0u"μs"))
```julia
if unit(time_per_div) == µs
```

2023-01-20 21:41 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        if typeof(time_offset) in (typeof(1u"μs"), typeof(1.0u"μs"))
```julia
if unit(time_offset) == µs
```

2023-01-20 21:41 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +            time_per_div = _convert_microseconds(time_per_div)
`_convert_microseconds` -> `_convert_to_microsecond`

2023-01-20 21:41 UTC, mofii commented on test/scope/agilent_dsox4034a.jl
> +    TcpInstruments.set_time_scale(scope, time_per_div=1.635μs, time_offset=30ps)
`set_time_scale` should be exported, right?
So there's no need to prepending with `TcpInstruments.`

2023-01-27 20:36 UTC, mofii requested changes
Nice!
See the comments within

2023-01-27 20:36 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    write(scope, "TIMEBASE:POSITION $time_offset") # alias for TIMEBASE:DELAY, which is obsolete
Write a helper function for the raw writes.
I guess my rule of thumb is to keep all functions / operations within a function at the same level. So if the function call other function to carry out work it should only call function to carry out work. Low level operations are wrapped in small helper functions.

2023-01-27 20:36 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    write(scope, "TIMEBASE:SCALE $time_per_div")
Same

2023-01-27 20:36 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    verify_time_offset(time_offset)
Nice!

2023-01-27 20:36 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +_convert_to_microseconds(microseconds) = string(ustrip(microseconds)) * "E-06"
This assumes the input is seconds, or?
A better version could be"
```julia
_convert_to_microseconds(time) = string(ustrip(uconv(s, time))) * "E-06"

```

2023-01-28 01:36 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +_convert_to_microseconds(microseconds) = string(ustrip(microseconds)) * "E-06"
This function is intended to take in Unitful microseconds and convert it to scientific notation for the scope to understand (does not accept the `μs` char, needs it in scientific notation per the datasheet). A better name would be `uniful_ms_to_scientific_notation(microseconds)`?

2023-02-02 00:45 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
@gita135 Are you converting millisecond to microsecond or microsecond to second?

2μs = 2e-06 second
2 second = 2e+6μs

I think you may need to convert time in 'μs' to seconds before sending it scope. The scope timebase will then be set in 'μs' because it does not like "μ' in scope command. Please check the datasheet.

2023-02-02 01:21 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
@deepaksnn Not converting the unit of measurement, but rather the format. The user enters `μs` (via Unitful) but bc the scope doesn't understand that format, we convert it to scientific format for the scope to understand. The param and return value is both microseconds

2023-02-02 19:47 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
Renamed it to `μs_to_scientific_e_notation()` for clarity

2023-02-02 19:51 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
Looks good 👍

2023-02-02 19:54 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
But why make the function so brittle?
What if the user inputs seconds instead of microseconds, then everything will silently fail, right?
As I see it, this version would be robust against the user using different units:
```julia
_convert_to_microseconds(time::Unitful.Time) = string(ustrip(uconvert(µs, time))) * "E-06"
```

Examples:
```julia
julia> using Unitful
julia> using Unitful: s, ms, µs


julia> _convert_to_microseconds(time::Unitful.Time) = string(ustrip(uconvert(µs, time))) * "E-06"
_convert_to_microseconds (generic function with 1 method)

julia> _convert_to_microseconds(1µs)
"1E-06"

julia> _convert_to_microseconds(1ms)
"1000E-06"

julia> _convert_to_microseconds(1s)
"1000000E-06"


julia> _convert_to_microseconds(1)
ERROR: MethodError: no method matching _convert_to_microseconds(::Int64)
Closest candidates are:
  _convert_to_microseconds(::Union{Quantity{T, 𝐓, U}, Level{L, S, Quantity{T, 𝐓, U}} where {L, S}} where {T, U}) at REPL[9]:1
Stacktrace:
 [1] top-level scope
   @ REPL[14]:1

```

2023-02-02 20:13 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +unitful_ms_to_sci_notation(microseconds) = string(ustrip(microseconds)) * "E-06"
I agree. This is correct. 
@gita135 Can you fix this and r-test it?

2023-02-02 21:03 UTC, mofii requested changes
I have some small change requests. 
I'd like tot rename the functions from `set_time_scale()` to `set_time_axis()` since we're both setting the scale (time per div) and the offset.

I made an example implementation of `set_time_axis()`

2023-02-02 21:03 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +function get_time_scale(scope::Instrument{<:AgilentScope})
Rename to `get_time_axis()`
I'd like the order of these functions to be like the example for `set_time_axis()`

2023-02-03 00:32 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +end
> Also, I see now why you only handle the microseconds case in the `μs_to_scientific_e_notation()` function - which is fine in this case!

Can i keep the name as `μs_to_scientific_e_notation()` or would you prefer `unitful_micro_s_to_e_notation_str()`?

2023-02-03 00:32 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +end
> > Also, I see now why you only handle the microseconds case in the `μs_to_scientific_e_notation()` function - which is fine in this case!
> 
> Can i keep the name as `μs_to_scientific_e_notation()` or would you prefer `unitful_micro_s_to_e_notation_str()` per your example code?

2023-02-03 01:06 UTC, gita135 commented on src/oscilloscope/agilent_common.jl
> +function get_time_scale(scope::Instrument{<:AgilentScope})
@mofii should I also have `get_time_per_div()` and `set_time_offset()` in addition or just `get_time_axis()`?

2023-02-03 01:23 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +end
> Can i keep the name as `μs_to_scientific_e_notation()` or would you prefer `unitful_micro_s_to_e_notation_str()` per your example code?

`μs_to_scientific_e_notation()` is fine

2023-02-03 06:29 UTC, mofii requested changes

2023-02-03 06:29 UTC, mofii commented on src/oscilloscope/agilent_common.jl
>  - `time_offset::Unitful.Time`: Offset time
We should somehow mention that these two arguments are not mandatory, that it will only set the ones which are fed to the function.

2023-02-03 06:29 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +# Returns
Returns
A named tuple with the fields:
- time_per_div
- time_offset

2023-02-03 06:29 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +# Returns
Ish

2023-02-03 06:29 UTC, mofii commented on src/TcpInstruments.jl
> +export get_time_axis, set_time_per_div, set_time_offset, set_time_axis
Only export get_time_axis and set_time_axis

2023-02-03 06:29 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +"""
I guess we can delete this docstring if we are not exporting the function

2023-02-03 06:29 UTC, mofii commented on src/oscilloscope/agilent_common.jl
>  """
Same for this one

2023-02-09 19:00 UTC, deepaksnn approved these changes
Looks Good 👍

2023-02-10 20:52 UTC, mofii commented
@gita135 This branch now has merge conflicts with main. Would you mind rebasing?

2023-02-10 20:56 UTC, mofii approved these changes
Good to go after the deletion of one line and a rebase to fix merge conflicts

2023-02-10 20:56 UTC, mofii commented on src/TcpInstruments.jl
> +export get_time_scale, set_time_scale
remove `_scale` exports

2023-02-10 21:15 UTC, merged