LAB-220: Unit tests for timeout function
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #223
Opened 2023-01-19 20:59 UTC by gita135

Wrote series of unit tests comparing `timeout1()` and `timeout2()`. Both execute successfully  in every case
Compared timings of execution of each to compare accuracy
Accuracy for each function is comparable, either implementation would suffice IMO.

2023-01-20 21:28 UTC, mofii requested changes
I get thousands of messages like this in the terminal when running these tests:
```julia
.┌ Error: Timed out after 0.1 s.
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:422
.┌ Error: Timed out after 0.1 s
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:384
.┌ Error: Timed out after 0.1 s.
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:422
.┌ Error: Timed out after 0.1 s
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:384
.┌ Error: Timed out after 0.1 s.
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:422
.┌ Error: Timed out after 0.1 s
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:384
.┌ Error: Timed out after 0.1 s.
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:422
.┌ Error: Timed out after 0.1 s
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:384
┌ Error: Timed out after 0.1 s.
└ @ TcpInstruments ~/local_src/TcpInstruments.jl/src/util.jl:422

```

Please suppress all of those error messages.

2023-01-20 21:28 UTC, mofii commented on test/runtests.jl
> +        function sleep_function(sleep_time::Float64)
Please squash this commit (d7055d133cda095b236a9acea3ae1c77e3106e1d) with the previous commit (7454d25d5b81d6a87b5742e9159fdf0dc3fad355 ) to make it easier to review the PR.

2023-01-20 21:28 UTC, mofii commented on test/runtests.jl
> +    @testset "timeout1 timeout2 unit tests" begin
Let's put all the timeout() tests into a separate file and call it `test_timeout.jl` and include it from here.

2023-01-20 21:28 UTC, mofii commented on test/runtests.jl
> +        @info  "timeout1_time < timeout2_time" timeout1_time < timeout2_time
What do we learn by printing these messages?

2023-01-20 21:28 UTC, mofii commented on test/runtests.jl
> +            @test isnothing(TcpInstruments.timeout1(f, timeout)) # Successful timeout/no retval
What's the comment 
```
# Successful timeout/no retval
```
There for? It's always the same comment whether or not the `sleep()` function returned within the timeout tim.

2023-01-20 21:28 UTC, mofii commented on test/runtests.jl
> +        sleep_time = 0.5
Please user shorter sleep times to speed up the tests. Slow tests means that they won't be used be the user, and we should test often when developing code. 
Besides, we have a limited amount of CI minutes per month.
Testing in milliseconds should work just as well as testing in seconds.

2023-01-26 23:21 UTC, gita135 commented on Project.toml
> +BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Since both timeout() function time executions are the same, no need to use @elpased now

2023-01-26 23:24 UTC, gita135 commented
> 

Turns out both `timeout()` functions were using the `@error` which is actually a  Logging macro, rather than throwing an `error` , which is why the errors were logging in the REPL. Now the fix to the proper `error` are being handled appropriately. This will also allow `clear_buffer()` to not throw an error (would need to add try/catch, but I can do that separately PR)

2023-01-26 23:25 UTC, gita135 commented on test/runtests.jl
> +        @info  "timeout1_time < timeout2_time" timeout1_time < timeout2_time
Removed them since timing is comparable

2023-01-27 20:23 UTC, mofii approved these changes
👍

2023-01-27 20:24 UTC, merged