LAB-184: Make Oscilloscopes use new struct for speed-up
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #226
Opened 2023-01-27 01:41 UTC by gita135

Includes: 
- `LAB-247:  Make all relevant state changing commands update the local state struct`
- `LAB-246: Make all dynamic calls to scope during get_data() use new struct`
- `LAB-242: get_data_bytes() uses new struct`
- `LAB-248: Make initialize(scope) populates the state struct`

Unable to add `LAB-241: Fix of LAB-200: add to settings struct the minimum sampling interval`: not possible to calculate this value (nonlinear relationship)

Unable to add `LAB-243: get_data_header() uses new struct` because the data returned by scope always includes the first two bytes as header byte. There is no separate command for header. This is a part of the data stream itself.

2023-01-27 01:49 UTC, gita135 commented
converting to draft until i rebase

2023-01-27 20:59 UTC, mofii approved these changes
Nice!
Let's merge this in!
@gita135 Can I get you to rebase the branch and solve the merge conflicts?

2023-01-30 19:56 UTC, gita135 commented
> Nice! Let's merge this in! @gita135 Can I get you to rebase the branch and solve the merge conflicts?

@mofii  done 👍

2023-01-30 20:43 UTC, mofii requested changes
@gita135 Thanks a lot for rebasing the code, now I can see the new additions!
See the comments within the the change requests. Thanks!

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/types.jl
> +    data_bytes::String
`data_bytes` -> `num_data_bytes'

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/types.jl
> +    waveform_preamble::String
Why are we storing these as strings?
That requires paring N times instead of 1 time.
I'd like this broken into their actual parameters

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/types.jl
> +    data_transfer_format::String
Maybe this one needs to be a string or could it be parsed?

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +    num_data_points = parse(Int64, scope.settings.data_bytes)
Store it as an Int in the settings struct instead of parsing here

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +end
Why write to the settings struct every time this read function is called?

This should be set just once on initialization and then only read from the settings struct thereafter.
This also shows that `settings.channels` should be renamed to `settings.valid_channels`

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
Same comment as above.

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
Reading the generic `get_valid_channels()` I'm a little worried these hardcoded function aren't doing what they should.
If `get_valid_channels()` is supposed to tell us which channels are enabled/showed on screen it seems strange to hardcode them to always be 1:4.
It looks like the generig function should be called during initialization?

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
> +        valid_channels = instr.settings.channels
Instead of interacting directly with the fields in the structs, make getter and setter functions to set and read the values.

2023-01-30 20:43 UTC, mofii commented on src/oscilloscope/agilent_common.jl
>  function get_waveform_info(instr::Oscilloscope{<:AgilentOscilloscopeModel}, ch::Integer)
All of these parameters should be parsed once and stored in the settings struct

2023-01-30 22:51 UTC, gita135 commented on src/oscilloscope/types.jl
> +    waveform_preamble::String
@mofii Can i implement a mini struct of `waveform_info` in the settings struct to prevent enlarging the settings struct? or just 11 more fields to the settings struct

2023-02-03 18:20 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +    instr.settings.data_transfer_format =  query(instr, "WAVEFORM:FORMAT?")
remove extra space

2023-02-03 19:16 UTC, deepaksnn commented on src/oscilloscope/agilent_common.jl
> +    coupling =  get_coupling(instr; chan=ch)
extra space

2023-02-09 19:01 UTC, deepaksnn approved these changes
👍

2023-02-10 20:46 UTC, mofii approved these changes
Let's merge!

2023-02-10 20:47 UTC, merged