Increased code speed for impedance analyzer
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #73
Opened 2021-11-08 22:53 UTC by stevenaleung

- Data transfer
- Frequency limit get() and set()
- Num data points get() and set()

2021-11-09 22:43 UTC, mofii reviewed
Very nice indeed!
I had a couple of small comments and questions in the Agilent4294A file

2021-11-09 22:43 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    write(ia, "FORM2")
A comment that states what FORM2 does could be useful down the road

2021-11-09 22:43 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    read(ia)
There could be a sanity check here to check that only the expected number of characters was read, and then throw an error if the behavior was off.

2021-11-09 22:43 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    read_data_file_header(ia)
Sometimes the functions are names read_ othertimes get_.
I actually like read_ since it makes it clearer that we are reading from a device and not just getting an attribute on an object in the local memory.
What are your thoughts?

2021-11-09 22:43 UTC, mofii commented on src/impedance_analyzer/all.jl
> +function get_frequency_limits(ia::Instr{T}) where T <: ImpedanceAnalyzer
Nice, clean refactor here!

2021-11-09 22:46 UTC, mofii requested changes
I see I have to approve or request changes for the comments to make it through to Slack.
It's a very nice PR!
I had some small comments and questions within.

2021-11-10 00:44 UTC, stevenaleung commented on src/impedance_analyzer/Agilent4294A.jl
> +# this function should be blocking
This function is blocking (lightly tested only)

2021-11-10 00:45 UTC, stevenaleung commented on src/impedance_analyzer/Agilent4294A.jl
> +    is_acquisition_complete = get_acquisition_status(ia)
I believe it is. Difficult to test off-site and without VPN working

2021-11-10 00:51 UTC, stevenaleung commented on src/impedance_analyzer/Agilent4294A.jl
> +    write(ia, "FORM2")
Changing this into a function instead: `set_data_output_to_float32()`

2021-11-10 00:54 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    write(ia, "FORM2")
nice

2021-11-10 00:56 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    read_data_file_header(ia)
You can take the same approach here, wrapping the "FORM2" and "OUTPDTRC" in meaningful names

2021-11-10 00:58 UTC, stevenaleung commented on src/impedance_analyzer/Agilent4294A.jl
> +    read_data_file_header(ia)
`read` and `write` make sense when we're communicating with the device. But it's low level and the user doesn't use these functions
I think it sounds more natural to have a user `get_channel()` and `set_channel()` than to `read_channel()` and `write_channel()`

2021-11-10 01:11 UTC, stevenaleung commented on src/impedance_analyzer/Agilent4294A.jl
> +    read(ia)
Done!

2021-11-10 07:20 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    read_data_file_header(ia)
Ok, sounds good to me

2021-11-10 07:22 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    read(ia)
👍

2021-11-10 07:27 UTC, mofii commented on src/impedance_analyzer/Agilent4294A.jl
> +    if length(data) != num_data_points
This is great, and it's tightly coupled with what I meant, which was to test the number of bytes read on line 150 (EOL).

2021-11-11 02:43 UTC, mofii approved these changes

2021-11-11 02:48 UTC, merged