ShowScopeData
Orchard-Ultrasound-Innovation/TcpInstruments.jl pull request #88
Opened 2021-12-09 09:06 UTC by mofii

This PR adds pretty printing to show(ScopeInfo) and show(ScopeData).

2021-12-10 21:45 UTC, stevenaleung requested changes
Nice unicode plots. Made a suggestion for the unit formatting functions

2021-12-10 21:45 UTC, stevenaleung commented on src/util.jl
> +end
Although this works, I found it a little difficult to follow (partly due to the many inputs and outputs)

Would something like the following be clearer:
```
function convert_to_best_prefix(input_value)
    power_of_1000 = round(log(1000, abs(input_value)))
    prefixes = OffsetArray(["p", "n", "μ", "m", "", "k", "M", "G"], -4:3)
    prefix = prefixes[power_of_1000]
    prefixed_unit = uparse(prefix * string(unit(input_value)))
    return uconvert(prefixed_unit, input_value)
end
```

This takes advantage of Unitful features and should also be generalizable

2021-12-10 21:45 UTC, stevenaleung commented on src/oscilloscope/scope_common.jl
> +    println("")
Cool plot!

2021-12-10 21:45 UTC, stevenaleung commented on test/runtests.jl
>      end
I also removed these tests in my PR because I found them to cause problems 😆

2021-12-13 21:00 UTC, mofii commented on src/util.jl
> +end
Yes, exactly! I was considering using OffsetArrays as well but I ran out of steam.
This is very elegant, I'll incorporate it :)

2021-12-15 11:04 UTC, mofii commented on src/util.jl
> +end
This looked like a cute little update but it took a surprising amount of work to get work properly (15 commits). 
There are still things that could be refactored but I think this feature has received enough love, for now :)

2021-12-15 19:55 UTC, stevenaleung requested changes
Don't want to add too much extra work because this is already pretty close. My main comments are on clarity/readability: methods of `convert_to_best_prefix()` don't have matching outputs and `get_power_of_1000()` has too many outputs

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +end
Wouldn't it be confusing to have the two `convert_to_best_prefix()` methods give different outputs?

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +- max_power: is the maximum power of 10 to convert to. Valid values: -4:3
```suggestion
- max_power: is the maximum power of 1000 to convert to. Valid values: -4:3
```

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +- max_power: is the maximum power of 10 to convert to. Valid values: -4:3
```suggestion
- max_power: is the maximum power of 1000 to convert to. Valid values: -4:3
```

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +    convert_to_best_prefix(input_value; base_unit::String = "", max_power = 3)
Would `max_power_of_1000` be too long of a name? `max_power` by itself doesn't seem informative enough

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +end
What if no `base_unit` is supplied? How will the returned prefix be used?

2021-12-15 19:55 UTC, stevenaleung commented on test/runtests.jl
> +            @test convert_to_best_prefix(1000u"V") ≈ 1000u"V"
Why wouldn't we want the output to be `1u"kV"`?

2021-12-15 19:55 UTC, stevenaleung commented on test/runtests.jl
> +            @test expected_number_and_unit(convert_to_best_prefix,  "s",  14e14, 1.4e6,  "Gs")
This has different behavior than `convert_to_best_prefix(14e14u"s")`

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +    return power_of_1000, unit_prefix, factor
Shouldn't this throw an error if `input_value == 0 || input_value == 1000` because `factor` is not defined?

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +end
To reduce the number of outputs we could split parts of this function out to `get_unit_prefix(power_of_1000)` and `get_scaling_factor(power_of_1000)`, then update the lines in `convert_to_best_prefix()`

2021-12-15 19:55 UTC, stevenaleung commented on src/util.jl
> +end
Should `base_unit` be a required input?

2021-12-15 20:14 UTC, mofii commented on test/runtests.jl
> +            @test convert_to_best_prefix(1000u"V") ≈ 1000u"V"
Because when this is the maximum value, then we'll for instance have 0 kV to 1 kV, instead of 0 V to 1000 V which I think is easier to read.

2021-12-15 20:19 UTC, mofii commented on src/util.jl
> +end
Yes, possibly. It could output the unit as well.

2021-12-15 20:22 UTC, mofii commented on src/util.jl
> +end
👍

2021-12-15 20:30 UTC, mofii commented on test/runtests.jl
> +            @test expected_number_and_unit(convert_to_best_prefix,  "s",  14e14, 1.4e6,  "Gs")
Yes, exactly. That was the purpose of that test - to show what it looks like when the `max_power` is not used.

2021-12-15 20:32 UTC, mofii commented on src/util.jl
> +    convert_to_best_prefix(input_value; base_unit::String = "", max_power = 3)
👍

2021-12-15 21:02 UTC, stevenaleung commented on test/runtests.jl
> +            @test convert_to_best_prefix(1000u"V") ≈ 1000u"V"
Gotcha, makes sense. Measurement data probably won't be round numbers though, so maybe `input_value <= 1200` would be more robust? (Randomly suggested 1200 as a cutoff because 1001 V would be converted to 1.001 kV even though it's very close to 1000 V)

2022-10-12 01:12 UTC, gita135 commented
Resolved merge issues, and removed testsets that were for deprecated functions

2022-10-15 00:09 UTC, gita135 commented
@mofii i am unable to request you as a reviewer since you are the creator of this PR

2022-11-03 19:14 UTC, mofii commented on src/oscilloscope/scope_common.jl
> +    println("")
👍

2022-11-18 23:46 UTC, gita135 commented on src/util.jl
> +end
@mofii is this resolved?

2022-12-02 18:49 UTC, gita135 commented
the unresolved (now resolved ) comments were from deprecated functions 👍

2022-12-02 19:12 UTC, mofii commented
That's great @gita135 ! Can I get you to attach an example of what the output currently looks like?

2022-12-02 19:17 UTC, mofii commented on src/oscilloscope/scope_common.jl
> +struct ScopeInfo
Why does the PR list so many new lines of code that look like it's code already present in main?
Is that code in a different file in the main branch?

2022-12-02 19:18 UTC, mofii commented on src/oscilloscope/scope_common.jl
> +using RecipesBase
Move all import/using to top-level file.

2022-12-02 19:31 UTC, gita135 commented on src/oscilloscope/scope_common.jl
> +struct ScopeInfo
Ah yes i see now. in the main branch, there is ```recipes.jl``` that contains all plotting functions (for scope) and ```types.jl``` that contains all structs and ```show()``` functions (for scope) and ```agilent_common.jl``` that contains all scope functions (```get_data()```, ```read_raw_waveform()``` etc) but in this PR, all was within the ```scope_common.jl``` file. I can move all the plotting functions from ```scope_common.jl``` to ```recipes.jl``` (for scope) and then delete ```scope_common.jl```  @mofii

2022-12-02 21:54 UTC, mofii commented on src/oscilloscope/scope_common.jl
> +struct ScopeInfo
I was just referring to non-plotting code, like the definition of `ScopeInfo` on line 7 to 24 in src/oscilloscope/scope_common.jl, and definition of ScopeData on line 43 to 47.

2022-12-06 00:44 UTC, gita135 commented
> That's great @gita135 ! Can I get you to attach an example of what the output currently looks like?
Had to move code around since main branch had different setup for scope code

![Screen Shot 2022-12-02 at 1 09 23 PM](https://user-images.githubusercontent.com/105512097/205777848-8f7f8635-6854-4d16-a537-c8360b325b7c.png)
![Screen Shot 2022-12-02 at 1 09 07 PM](https://user-images.githubusercontent.com/105512097/205777873-0db40101-a7d2-4d4e-ab43-895c7d65e36b.png)

2022-12-10 00:21 UTC, gita135 commented
> > That's great @gita135 ! Can I get you to attach an example of what the output currently looks like?
> > Had to move code around since main branch had different setup for scope code
> 
> ![Screen Shot 2022-12-02 at 1 09 23 PM](https://user-images.githubusercontent.com/105512097/205777848-8f7f8635-6854-4d16-a537-c8360b325b7c.png) ![Screen Shot 2022-12-02 at 1 09 07 PM](https://user-images.githubusercontent.com/105512097/205777873-0db40101-a7d2-4d4e-ab43-895c7d65e36b.png)

@mofii pinging 🔔  since cant request you as reviewer

2022-12-12 18:52 UTC, mofii commented
Great, @gita135, happy to see this is working!
Merging now!

2022-12-12 19:00 UTC, merged